// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DKbWqdUM2a-Yix2cuy5H1M_C-CC1Gf8',
    appId: '1:1045229348102:web:29d57a2683460edb982a87',
    messagingSenderId: '1045229348102',
    projectId: 'login-da500',
    authDomain: 'login-da500.firebaseapp.com',
    storageBucket: 'login-da500.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX--XUsy9wCgrnJgTWGAQoW36y_L5Npp4',
    appId: '1:1045229348102:android:d108c3a358428927982a87',
    messagingSenderId: '1045229348102',
    projectId: 'login-da500',
    storageBucket: 'login-da500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6jpHqBnBMFjTMqJx_wKCkhrUHZdaNKBg',
    appId: '1:1045229348102:ios:0479205761a58e8e982a87',
    messagingSenderId: '1045229348102',
    projectId: 'login-da500',
    storageBucket: 'login-da500.appspot.com',
    iosBundleId: 'com.example.login',
  );
}
